---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver: 
      box: dummy
      box_url: https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
      provider: aws
      vagrantfile_erb: Vagrantfile.erb
      #vagrantfiles: Vagrantfile.rb

suites:
  - name: reveal_cookbook
    run_list:
      - recipe[apache2::default]
    attributes: